version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "AWS CLI version:"
      - aws --version
      - echo Logging in to AWS CodeArtifact...
      - echo Getting CodeArtifact token...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 257394474969 --region us-west-2 --query authorizationToken --output text)

  build:
    commands:
      - echo Build started on `date`
      - echo Verifying settings.xml is accessible...
      - ls -l settings.xml || (echo "settings.xml not found!" && exit 1)
      - echo "Running Maven compile"
      - mvn -s settings.xml compile
      - echo "Running Maven tests"
      - mvn -s settings.xml test
  post_build:
    commands:
      - echo "Packaging the build"
      - mvn -s settings.xml package
      - echo "Build completed on `date`"

  artifacts:
    files:
      - target/*.jar  

