version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing AWS CLI v2
      - yum install -y unzip 
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - echo Logging in to AWS CodeArtifact...
      - aws codeartifact login --tool mvn --repository nextwork-repo --domain nextwork --domain-owner 257394474969 --region us-west-2

  build:
    commands:
      - echo Build started on `date`
      - mvn compile

  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package

artifacts:
  files:
    - target/nextwork-web-project.war
  discard-paths: no
