version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Installing AWS CLI and logging into CodeArtifact
      - aws --version
      - aws codeartifact login --tool mvn --repository nextwork-devops-cicd --domain nextwork --domain-owner 257394474969 --region us-west-2

  build:
    commands:
      - echo Build started on `date`
      - mvn compile
      - echo Test the code 
      - mvn test 
  post_build:
    commands:
      - echo Build completed. Packaging...
      - mvn package

artifacts:
  files:
    - target/*.jar   # or *.war depending on your output

reports:
  junitReports:
    files:
      - target/surefire-reports/**/*.xml
    base-directory: target
    discard-paths: yes      
