version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "AWS CLI version:"
      - aws --version
      - echo Logging in to AWS CodeArtifact...
      - echo Getting CodeArtifact token...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 257394474969 --region us-west-2 --query authorizationToken --output text)

  build:
    commands:
      - echo Build started on date
      - echo Verifying settings.xml is accessible...
      - pwd
      - ls -l  
      - ls -l settings.xml || (echo "settings.xml not found!" && exit 1)
      - settings.xml :<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">


